name: Taskforce Mailer Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Rayvical
          POSTGRES_DB: taskforce_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Setup environment variables
        run: |
          cp env.example .env
          sed -i 's#^DATABASE_URL=.*#DATABASE_URL=postgresql://postgres:Rayvical@localhost:5432/taskforce_test#' .env || echo "DATABASE_URL=postgresql://postgres:Rayvical@localhost:5432/taskforce_test" >> .env
          sed -i 's#^REDIS_URL=.*#REDIS_URL=redis://localhost:6379#' .env || echo "REDIS_URL=redis://localhost:6379" >> .env
          sed -i 's#^JWT_SECRET=.*#JWT_SECRET=test-jwt-secret-key#' .env || echo "JWT_SECRET=test-jwt-secret-key" >> .env
          sed -i 's#^GMAIL_CLIENT_ID=.*#GMAIL_CLIENT_ID=test-client-id#' .env || echo "GMAIL_CLIENT_ID=test-client-id" >> .env
          sed -i 's#^GMAIL_CLIENT_SECRET=.*#GMAIL_CLIENT_SECRET=test-client-secret#' .env || echo "GMAIL_CLIENT_SECRET=test-client-secret" >> .env
          sed -i 's#^OPENROUTER_API_KEY=.*#OPENROUTER_API_KEY=test-api-key#' .env || echo "OPENROUTER_API_KEY=test-api-key" >> .env
          sed -i 's#^CONSENT_CONTENT=.*#CONSENT_CONTENT=false#' .env || echo "CONSENT_CONTENT=false" >> .env

      - name: Build packages
        run: pnpm build

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL... ($i/30)"
            sleep 2
          done

      - name: Run database migrations
        working-directory: apps/backend
        env:
          DATABASE_URL: postgresql://postgres:Rayvical@localhost:5432/taskforce_test
        run: pnpm prisma migrate deploy

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:Rayvical@localhost:5432/taskforce_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-jwt-secret-key
          GMAIL_CLIENT_ID: test-client-id
          GMAIL_CLIENT_SECRET: test-client-secret
          OPENROUTER_API_KEY: test-api-key
          CONSENT_CONTENT: false
        run: pnpm test:ci

      - name: Run linting
        run: pnpm lint

  build-windows:
    runs-on: windows-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build application
        run: pnpm build

      - name: Install Electron Builder
        run: pnpm add -D electron electron-builder -w

      - name: Create Windows installer
        run: |
          cd electron-app
          npm install
          npx electron-builder --win nsis --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: electron-app/dist/*.exe

  build-macos:
    runs-on: macos-latest
    needs: test
    strategy:
      matrix:
        arch: [x64, arm64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build application
        run: pnpm build

      - name: Install Electron Builder
        run: pnpm add -D electron electron-builder -w

      - name: Create macOS installer
        run: |
          cd electron-app
          npm install
          # Create a simple placeholder for dmg background if it doesn't exist
          mkdir -p assets
          if [ ! -f assets/dmg-background.png ]; then
            echo "Creating placeholder dmg-background.png"
            # Create a simple 1x1 transparent PNG as placeholder
            echo -e '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\x27\x00\x00\x00\x00IEND\xaeB`\x82' > assets/dmg-background.png
          fi
          npx electron-builder --mac dmg zip --${{ matrix.arch }} --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer-${{ matrix.arch }}
          path: electron-app/dist/*.{dmg,zip}

  build-linux:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build application
        run: pnpm build

      - name: Install Electron Builder
        run: pnpm add -D electron electron-builder -w

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot rpm

      - name: Create Linux installer
        run: |
          cd electron-app
          npm install
          npx electron-builder --linux AppImage deb --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: electron-app/dist/*.{AppImage,deb}

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    if: always() # Run even if some builds fail
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: windows/
        continue-on-error: true

      - name: Download macOS x64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-installer-x64
          path: macos-x64/
        continue-on-error: true
      
      - name: Download macOS ARM64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-installer-arm64
          path: macos-arm64/
        continue-on-error: true

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-installer
          path: linux/
        continue-on-error: true

      - name: List available artifacts
        run: |
          echo "Available artifacts:"
          find . -name "*.exe" -o -name "*.dmg" -o -name "*.zip" -o -name "*.AppImage" -o -name "*.deb" | head -20

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: 🚀 Taskforce Mailer ${{ github.ref_name }} - Ready to Install
          body: |
            ## 🚀 Taskforce Mailer ${{ github.ref_name }}
            
            ### 📦 Available Downloads
            - **Windows**: Windows installer (.exe)
            - **Linux**: AppImage and .deb packages
            - **macOS**: DMG and ZIP files (Intel and Apple Silicon)
            
            ### 🔧 What's New
            - Fixed Electron app build configuration
            - Added proper author email and repository fields
            - Removed icon requirements for easier building
            - Improved cross-platform compatibility
            
            ### 📋 Installation
            1. Download the appropriate installer for your platform
            2. Run the installer and follow the setup wizard
            3. Launch Taskforce Mailer from your applications
            
            ### 🐛 Issues Fixed
            - Missing author email error for Linux .deb packages
            - Missing repository field warnings
            - Missing icon file errors
            - Build process failures
          draft: false
          prerelease: false
          files: |
            windows/**/*
            macos-x64/**/*
            macos-arm64/**/*
            linux/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

